### ISSUE TITLE
Do you have a document on the "Vue CRUD communication specification"?

### ISSUE THREAD

**Issue by baimingze** [what-crud/vue-crud#10]
Great work.

Do you have a document on the "Vue CRUD communication specification"?

**Comment by szczepanmasny** [comment]
Hi, thanks.
I don't quite understand what you mean. Unfortunately, I'm just starting my adventure with GitHub and contributing to Open Source tools. Do you mean a communication tool such as Skype or Discord? Or maybe about the forum related to the project? I will be grateful if you advise me.
