### ISSUE TITLE
crm demo login failed?

### ISSUE THREAD

**Issue by yeahnoob** [what-crud/vue-crud#25]
Yesterday, it's OK.

Today, I cannot login with the given guest user account {user: 'guest@vue-crud.com', pw: 'ajSGenC0'} , and error message pop out 'Login attempt unsuccessful' .

Is that REST API service stop working now?

**Comment by szczepanmasny** [comment]
I'm sorry. I corrected it temporarily. But I have to fix a bug in my API so that the situation doesn't happen again.
