### ISSUE TITLE
[Question] - General Questions

### ISSUE THREAD

**Issue by go4cas** [what-crud/vue-crud#26]
I am keen to try out your template. But, I have a few questions:

- Looking at the api config, it seems one cannot specify multiple api configurations, example: in my use case I have a separate API for my data entities, and one specifically for auth. How would this work, using this template?
- I have a JWT workflow for my auth, i.e. `login` will get an access and refresh tokens. WHen the token expires, I will call `refresh` to get a new token. `Logout` will delete from localstorage. How will I be able to implement this workflow, using your template? Or, I can use my own auth mechanism?
- Are you planning to add any of the other vuetify components to Field Options? Example: Autocomplete, Slider, etc?
- Can the table view include custom components in cells? Example: I have a UserCard component (which includes name, job title, avatar, etc) that I want to display in the table cell.
- There are some sections missing in the documentation. When will these be added?

**Comment by szczepanmasny** [comment]
- Unfortunately, there is no possibility to create custom authentication yet. I am planning to create a config/auth.js file support for this purpose.
- In older versions, token refresh support was added, but I couldn't deal with situations when some requests (with old token attached) were sent between the sending of a new token request and saving it in Local Storage. Do you have an idea how to solve it? Maybe the old token should be valid for some time after creating a new one?
- autocomplete is hidden under the name 'select'. What would be the function of the slider field? Support for multiple files/images? I plan to extend the "File" field type to support multiple files.
- I can add slot support table cells. Another option is using custom buttons - you can add your own button in the actions column, which will redirect you to your component.
- Unfortunately, the bigger the project, the more things I have to correct and I can't keep up with the fixes and improvements. I also have less and less time for this project. I will try to finish the documentation in May, but I'm not sure if I will succeed.

**Comment by szczepanmasny** [comment]
But if you want to contribute in the project and solve the problems you found, I would be very grateful.
