### ISSUE TITLE
New field types

### ISSUE THREAD

**Issue by szczepanmasny** [what-crud/vue-crud#29]

**Comment by szczepanmasny** [comment]
- multiple files

**Comment by bonzai86** [comment]
Hi szczepanmasny,

great work! Could you implement a multi select field (e.g. tags). Maybe using vue-select compontent (https://github.com/sagalbot/vue-select).
Fields "time" and "datetime" should provide a picker instead of mask.

**Comment by szczepanmasny** [comment]
Hi, I solved this problem in another way. If you want to manage with pivot/intersection table you can define itemElements array and pass it to the crud component.
Yesterday I have created slots for custom item details fields too. I know your idea is good but I'm not able to create all missing features myself, so I think that solution with slots is good way to solve problem with missing functions in Vue CRUD.
