### ISSUE TITLE
CRM example Child Tables

### ISSUE THREAD

**Issue by chemeng** [what-crud/vue-crud#56]
In the CRM example, the child tables are not populated in the goToItem view due to the getChild action never getting dispatched. The script errors out due to no data existing when the childrenList() function is called. 

It feels like part of the code is missing there. 

PS: _Great project, thank you for the source!_

**Comment by hizmarck** [comment]
Perhaps that We had the same problem, I checked the code of ChildrenTable.vue and add this code:

`<span v-else>{{ field | cropped }} </span>`

Line 157,

**Comment by hizmarck** [comment]
After a time I've searched the real problem for this behavior, 

`columnTextModes` is a method that required `props` from v-table, something like this `columnTextModes(props)[key]`, but I think this is not the better solutions perhaps created a new component would be the best and then use a computed property.  

@szczepanmasny

**Comment by szczepanmasny** [comment]
Hi,
thank you very much for finding this bug.

I've made a lot of mess with this `columnTextModes` property / method. I applied the corrections and, by the way, I have refactored the code in `ChildrenTable.vue` using the existing `DataTableRow.vue` component.
Could you check if the patches have solved the problem?

@hizmarck , @chemeng  If you notice any errors in the code or you have an idea how to improve the application, I will be very happy if you contribute in the project
