### ISSUE TITLE
API url not changing no matter what I do

### ISSUE THREAD

**Issue by vlom31** [what-crud/vue-crud#57]
**Describe the bug**

I changed the API url in both api.js and auth.js, yet Chrome is still somehow calling 127.0.0.1:8000

> edit auth.js and api.js to change API url
> npm load-template crm
> npm run serve
> try to login
> check chrome console
> Failed to load resource: 127.0.0.1:8000 net::ERR_CONNECTION_REFUSED
> clear all caches
> try incognito

**Expected behavior**
the login should call the new url specified.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: mac Os - Catalina 10.15
 - Browser : Chrome 
 - Version 77.0.3865.75

**Comment by szczepanmasny** [comment]
Hi, `npm load-template [template-name]` command loads template that has its own config files, so when you use this command your config files are overwritten with these example files. Try to reverse the order of operations - first use the command and then save the config files
