### ISSUE TITLE
Question on using simple-crud

### ISSUE THREAD

**Issue by dgleba** [what-crud/vue-crud#72]
**Describe the issue**
-Blank browser screen.
-index.js - Uncaught RangeError: Duplicate use of selection JSON ID cell
 
**To Reproduce**
-on ubuntu 16.04 command line server
-mkdir /srv/file/test
-cd /srv/file/test
-mkdir vuecrud
-git clone https://github.com/what-crud/vue-crud.git vc-k7016
-cd vc-k7016
-npm i
-npm run load-template simple-crud
-npm run serve
-get error above.

**Expected behavior**
see the crud on screen

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  I tried two. win10 and ubuntu 16.04 server
 - Browser chrome in win. firefox on ubuntu xfce4
 - Version - firefox 70.0

**Smartphone (please complete the following information):**

**Additional context**
Just trying to use it as delivered.

![2019-11-04 13_14_07-vue-crud](https://user-images.githubusercontent.com/4622715/68146106-4049ab80-ff05-11e9-8962-4e52ee9d0826.jpg)
--
![2019-11-04 13_40_33-redwe458 desk@ad - AnyDesk](https://user-images.githubusercontent.com/4622715/68148034-404baa80-ff09-11e9-92f7-869482441614.jpg)

**Comment by szczepanmasny** [comment]
Hi, 
Thank you for reporting the bug.
It was a problem with tiptap library and package-lock.json file.
Now everything should work.

Regards
Szczepan
