### ISSUE TITLE
Major Security Flaw

### ISSUE THREAD

**Issue by GHBSSR** [what-crud/vue-crud#90]
I was able to pretty easily 'hack' the demo site by changing my permissions locally.

1. Open Chrome Devtools 'CTRL+SHIFT+I'
2. Go the application tab and click the Local Storage
3. Changed 'Permissions' to ADMIN
4. Refresh page

I can now view admin content as the site recognizes me as such. Interestingly I was able to view the admin 'initial' password and it had not been changed. I was able to login as the admin and change the user data contained inside of it.

**Comment by GHBSSR** [comment]
You're welcome

**Comment by szczepanmasny** [comment]
Thanks for your issue.
I hope I have dealed with it.
I closed your issue because I was scared that it may cause that too many users would check this problem at the same time and then I wouldn't be able to solve problem.
